### PR TITLE
Moved react components into app/component/ and fixed dependancies bro…

### LINKED ISSUE #70: Restructure directory
Make component folder in app/ and move react components there. Involves fixing dependencies for new directory structure.

### PR DESCRIPTION
**Pull request by ak505188**
Closes #70 
Created containers/ for smart components.

### CODE REVIEW

**Comment by stefaneng** [comment]
What do you think about moving the App component into a `container` folder for the smart components like the examples on Redux?

Here is an example:
http://redux.js.org/docs/basics/ExampleTodoList.html#smart-components

Here is documentation on smart components vs dumb components.
http://redux.js.org/docs/basics/UsageWithReact.html#smart-and-dumb-components

**Comment by ak505188** [comment]
I'm all for it. So from my understanding our only smart component would be App.js right?

**Comment by stefaneng** [comment]
Yup, exactly.

**Comment by ak505188** [comment]
So only difference is that App.js would be in a containter/ folder right?

**Comment by stefaneng** [comment]
Yeah, we may have some more components in `container/` at some point, but for now just `App.js`.

**Pull request merged**
